# Build pipeline
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

variables:
- group: AzureKeyVaultSecrets

jobs:
- job: DevOpsForAIJob
  pool:
    vmImage: 'Ubuntu 16.04'
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'   

  - task: Bash@3
    displayName: 'Install Requirements'
    inputs:
      targetType: filePath
      filePath: 'environment_setup/install_requirements.sh'
      workingDirectory: 'environment_setup'

  - script: | 
      echo 'Login to   Azure Account'
      az login --service-principal -u $(spidentity) --password $(spsecret) --tenant $(sptenant)   
      az account set --subscription $(subscriptionid)
      displayName: 'Login to Azure'

  - script: |
      sed -i 's#"subscription_id": "<>"#"subscription_id": "$(subscription_id)"#g' aml_config/config.json
      displayName: 'replace subscription value'

  - script: |
      'pytest tests/unit/data_test.py'
      displayName: 'Data Quality Check'

  - script: 'python aml_service/00-WorkSpace.py'
    displayName: 'Get or Create workspace copy'

  - script: 'python aml_service/10-TrainOnLocal.py'
    displayName: 'Train on Local'

  - script: 'python aml_service/15-EvaluateModel.py'
    displayName: 'Evaluate Model'

  - script: 'python aml_service/20-RegisterModel.py'
    displayName: 'Register Model'

  - script: 'python aml_service/30-CreateScoringImage.py'
    displayName: 'Creating scoring image'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: devops-for-ai'
    inputs:
      ArtifactName: 'devops-for-ai'
      publishLocation: 'container'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      TargetPath: '$(Build.ArtifactStagingDirectory)'


